name: Sync from xwalk to forms (monthly)

on:
  schedule:
    - cron: "0 0 1 * *" # Runs at 00:00 on the 1st of every month
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/adobe-rnd/aem-boilerplate-xwalk.git
          git fetch upstream

      - name: Create sync branch and rebase
        run: |
          BRANCH="sync-xwalk-$(date +'%Y-%m-%d')"
          git checkout -b "$BRANCH" origin/main

          set +e
          git rebase upstream/main
          while [ $? -ne 0 ]; do
            echo "Merge conflicts detected — auto-committing resolution..."
            git add -A
            git commit -m "Auto-resolve conflict during monthly sync with xwalk"
            git rebase --continue
          done
          set -e

          git push origin "$BRANCH"
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore:monthly sync from xwalk" \
            --body "This PR syncs changes from [aem-boilerplate-xwalk](https://github.com/adobe-rnd/aem-boilerplate-xwalk) into this fork.  
            - Branch: $BRANCH_NAME  
            - All conflicts (if any) were auto-committed during rebase." \
            --base main \
            --head "$BRANCH_NAME" \
            || echo "PR may already exist. Skipping..."
